### ISSUE TITLE
tidak ada pasword

### ISSUE THREAD

**Issue by hilmanbaliaw** [Allviyan/BotKntD#1]
tidak menemukan pasword di web https://shortid.co/fZFa6

mohon paswordnya untuk bot facebook 🙏

**Comment by mbilalk572** [comment]
botkntd is the password

**Comment by mbilalk572** [comment]
> tidak menemukan pasword di web https://shortid.co/fZFa6
> 
> mohon paswordnya untuk bot facebook 
botkntd is the pass
