### ISSUE TITLE
Botkntd

### ISSUE THREAD

**Issue by Aqeelbhayo** [Allviyan/BotKntD#9]
Bro botkntd user name and password please

**Comment by Jsjsiososooeoeoieiekekjej** [comment]
Fake. I'd. Banawo. Fast net. And. Fast. vPN SkyVPN

**Comment by Aqeelbhayo** [comment]
Fake id Facebook ke bnao bro help kerdy kindly

**Comment by Jsjsiososooeoeoieiekekjej** [comment]
My. Whttsapp. Number 03347231035
